### PR TITLE
Unset the internal connection when closing a connection explicitly 

### PR DESCRIPTION
**Pull request by hollodotme**
to avoid E_WARNING when destructor tries to close the connection again
Fixed some type hints in PHPDoc comments
Removed @method close() and @method rawList() in FtpClient
Removed unused "use \Closure"

### CODE REVIEW

**Comment by hollodotme** [comment]
For explanation: I have multiple jobs in a kind of queue. Every jobs needs a single FtpClient instance/connection. When one job has finished I want to close its connection explicitly. When I do so, there are a E_WARNINGs triggered at the end of my queue script, because the destructor of the FtpClient tries to close its connection again because the `conn` member is not resolving to `false`.

**Comment by hollodotme** [comment]
Any chance you'll merge this soon?

**Comment by Nicolab** [comment]
Thank you @hollodotme 

_Sorry for the delay!_

**Comment by hollodotme** [comment]
@Nicolab No problem. Thanks!

**Comment by Nicolab** [comment]
:+1:

**Pull request merged**
