### PR TITLE
rmdir error

### PR DESCRIPTION
**Pull request by hldjlz**
function remove was error in line 450.
$path was absolute path.

### CODE REVIEW

**Comment by AmraniCh** [comment]
Maybe the directory you're willing to remove is a direct sub directory of the current pointing directory, the `rmdir `command according to the [RFC959](https://datatracker.ietf.org/doc/html/rfc959#section-4) spec mentions that if the path was relative the `rmdir `command will remove the sub directory of the current directory, if the path is absolute the directory specified in the pathname argument will be removed (if its a directory type of course).

The change you made cannot be taking because is violate the spec, thus violate the majority of the FTP servers implementations.

Try to change the current working directory to the top level directory with the `chdir`, and try again with the absolute path.

```php
$ftp->chdir('.');
```

**Comment by Nicolab** [comment]
Thanks @hldjlz but @AmraniCh has detailed it very well.

**Comment by hldjlz** [comment]
Thanks.

**Comment by hldjlz** [comment]
> Maybe the directory you're willing to remove is a direct sub directory of the current pointing directory, the command according to the [RFC959](https://datatracker.ietf.org/doc/html/rfc959#section-4) spec mentions that if the path was relative the command will remove the sub directory of the current directory, if the path is absolute the directory specified in the pathname argument will be removed (if its a directory type of course).`rmdir ``rmdir `
> 
> The change you made cannot be taking because is violate the spec, thus violate the majority of the FTP servers implementations.
> 
> Try to change the current working directory to the top level directory with the , and try again with the absolute path.`chdir`
> 
> ```
> $ftp->chdir('.');
> ```
my code:
```
$remotePath = "Uploads/images";
if($this->ftp->isDir($remotePath)){
    $this->ftp->rmdir($remotePath);
}
```
but it will go into a endless loop

**Comment by AmraniCh** [comment]
Try this :

```php
$ftp = new FtpClient();
$remotePath = "./Uploads/images";
if($ftp->isDir($remotePath)){
    $ftp->rmdir($remotePath);
}
```

**Comment by hldjlz** [comment]
still cannot working
image

**Comment by hldjlz** [comment]
> Try this :
> 
> ```
> $ftp = new FtpClient();
> $remotePath = "./Uploads/images";
> if($ftp->isDir($remotePath)){
>     $ftp->rmdir($remotePath);
> }
> ```
this is test dir, it's empty, but still cannot remove by $ftp->rmdir()
image
image
image

**Comment by hldjlz** [comment]
> Try this :
> 
> ```
> $ftp = new FtpClient();
> $remotePath = "./Uploads/images";
> if($ftp->isDir($remotePath)){
>     $ftp->rmdir($remotePath);
> }
> ```
I just created a test directory, it's empty, but still cannot remove by $ftp->rmdir()
image
image
image

**Comment by AmraniCh** [comment]
Okey, if the directory is empty and the `rmdir` not working, maybe you don't have permissions over the directory, to be sure what goes wrong try this :

```php
$ftp = new FtpClient();

$remotePath = "./Uploads/images";

if($ftp->isDir($remotePath)){
    set_error_handler(function () {
        print_r('ftp error : ' . func_get_args()[1]);
    });

    $ftp->rmdir($remotePath);

    restore_error_handler();
}
```

**Pull request closed without merging**
